### ISSUE TITLE
Remove dependency on Apache's Commons-Lang

### ISSUE THREAD

**Issue by mannodermaus** [Workday/postman#12]
This library includes all of `commons-lang` because of one single usage in [capitalizing String input](https://github.com/Workday/postman/blob/master/postman/src/main/java/com/workday/postman/codegen/BoxableSaveStatementWriter.java). Since the library footprint of `commons-lang`, with its roundabout 3000 methods, is comparatively big in relation to its usefulness in Postman, I am proposing to get rid of the dependency and roll our own implementation of StringUtils.capitalize().

**Comment by ndtaylor** [comment]
Sounds reasonable.
