### ISSUE TITLE
Split into processor & core

### ISSUE THREAD

**Issue by mannodermaus** [Workday/postman#18]
This library includes a dependency on `javawriter` for its compile-time code generation. Since there is only one artifact to include for both the processor and core, this dependency is shipped in the final package as well. Please consider splitting up the library into two separate modules, to have inclusion work akin to other code generation libraries, like so:

```
compile "com.github.Workday:postman:<version>"
apt "com.github.Workday:postman-processor:<version>"
```

Only the processor module would then require the dependency on javawriter.

**Comment by ndtaylor** [comment]
Shouldn't be too hard. All of the code generation stuff has already been partitioned into a separate package (codegen), so all we have to do is put that in a separate module (and move Names.java, which is in codegen and shouldn't be).

**Comment by mannodermaus** [comment]
Awesome! I can create a PR later this week, if you like.

**Comment by ndtaylor** [comment]
Works for me. Pull requests are always welcome.

**Comment by mannodermaus** [comment]
Here is the PR. I haven't touched the README yet to extend the *How to Use Postman" section with the new artifact configuration, though.
