### ISSUE TITLE
Postman version 1.3 Parcelers disappear

### ISSUE THREAD

**Issue by KennethNickles** [Workday/postman#25]
I upgraded to version 1.3 and the parcelers disappear. When I downgrade to 1.2 they reappear. Makes me believe the processor isn't running in 1.3, or something changed that is causing the processor to not run on my particular build.

**Comment by ndtaylor** [comment]
Indeed. Version 1.3 split postman out into two artifacts, one of which is the processor. Check the readme for how to uptake the new artifact scheme.
